# Generated by Django 6.0.6 on 2026-06-19 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('delivery', '0001_initial'),
        ('discounts', '0001_initial'),
        ('products', '0004_product_brand_alter_product_description_productcolor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('payment_failed', 'Payment Failed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('address_snapshot', models.JSONField(default=dict)),
                ('delivery_type', models.CharField(default='normal', max_length=20)),
                ('delivery_date', models.CharField(blank=True, max_length=20)),
                ('delivery_cost', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('cod', 'Cash on Delivery')], default='online', max_length=10)),
                ('payment_token', models.CharField(blank=True, max_length=200)),
                ('payment_tracking_code', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('products_total', models.PositiveIntegerField(default=0)),
                ('insurance_total', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('discount_code_amount', models.PositiveIntegerField(default=0)),
                ('gift_card_amount', models.PositiveIntegerField(default=0)),
                ('final_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address')),
                ('delivery_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliverytimeslot')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discountcode')),
                ('gift_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.giftcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.CharField(blank=True, max_length=500)),
                ('color_name', models.CharField(blank=True, max_length=100)),
                ('guarantee_text', models.CharField(blank=True, max_length=300)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('insurance_name', models.CharField(blank=True, max_length=200)),
                ('insurance_price', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
