# Generated by Django 6.0.6 on 2026-06-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_product_brand_alter_product_description_productcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='Paragraphs separated by \\n\\n')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compare_description', to='products.category')),
            ],
        ),
    ]
