# Generated by Django 6.0.6 on 2026-07-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('franchise_type', models.CharField(choices=[('store', 'فروشگاهی (حضوری)'), ('online', 'اینترنتی (آنلاین)'), ('hybrid', 'ترکیبی (حضوری + آنلاین)')], max_length=10)),
                ('investment_range', models.CharField(choices=[('under_50m', 'کمتر از ۵۰ میلیون تومان'), ('50m_150m', '۵۰ تا ۱۵۰ میلیون تومان'), ('150m_300m', '۱۵۰ تا ۳۰۰ میلیون تومان'), ('above_300m', 'بیش از ۳۰۰ میلیون تومان')], max_length=15)),
                ('has_sales_experience', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درخواست نمایندگی',
                'verbose_name_plural': 'درخواست\u200cهای نمایندگی',
                'ordering': ['-created_at'],
            },
        ),
    ]
