# Generated by Django 6.0.6 on 2026-06-19 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.TextField(blank=True)),
                ('map_title', models.CharField(blank=True, max_length=300)),
                ('map_subtitle', models.CharField(blank=True, max_length=300)),
                ('map_iframe_src', models.TextField(blank=True)),
                ('map_lat', models.FloatField(default=35.7)),
                ('map_lng', models.FloatField(default=51.4)),
                ('support_phones', models.JSONField(default=list)),
                ('main_phone', models.CharField(blank=True, max_length=30)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='ContactSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contact/slider/')),
                ('alt', models.CharField(default='تماس با بست', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Slider',
            },
        ),
        migrations.CreateModel(
            name='ContactSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('resolved', 'حل شده'), ('closed', 'بسته')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contact/attachments/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contact.contactticket')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_staff', models.BooleanField(default=False)),
                ('staff_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='contact.contactticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
