# Generated by Django 6.0.6 on 2026-06-19 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('alley', models.CharField(blank=True, max_length=200)),
                ('plaque', models.CharField(max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(max_length=10)),
                ('receiver_type', models.CharField(choices=[('self', 'Self'), ('other', 'Other')], default='self', max_length=10)),
                ('receiver_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('receiver_phone', models.CharField(blank=True, max_length=15)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
