# Generated by Django 6.0.6 on 2026-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
