# Generated by Django 6.0.6 on 2026-06-19 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermsMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('last_updated', models.CharField(blank=True, max_length=20)),
                ('hero_title', models.CharField(blank=True, max_length=300)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('wallet_title', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Terms Metadata',
                'verbose_name_plural': 'Terms Metadata',
            },
        ),
        migrations.CreateModel(
            name='WalletTermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Wallet Terms Section',
                'verbose_name_plural': 'Wallet Terms Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Term Acceptance',
                'verbose_name_plural': 'Term Acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
