# Generated by Django 6.0.6 on 2026-07-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_description_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='hex',
            field=models.CharField(max_length=50),
        ),
    ]
